%% G4 Mode 7 - Continuous display, strobe moved to the ADC0 signal
% External voltage on ADC0 drives the x frame index (Mode 7, "ADC sets index").
%
% WHY THIS VERSION EXISTS
% -----------------------
% The old script strobed the stimulus with stopDisplay/startDisplay. Every
% startDisplay in Mode 7 re-shows the last ADC value latched in the FPGA
% sample-and-hold, so for ~10 ms the animal saw the PREVIOUS bar position
% before the ADC re-synced. Mode 7 also ignores live host commands
% (setPositionX/Y, setGain, allOff) once running, so the flash could not be
% blanked from MATLAB.
%
% FIX: never stop the display. Run ONE continuous startDisplay for the whole
% trial so the ADC converts continuously and is never stale. The strobe
% (ON = live heading, OFF = dark) is produced on the ADC0 SIGNAL instead, by
% the FicTrac-consumer script that generates the closed-loop voltage
% (see fictrac_strobe_gate.py). The animal then only ever sees darkness or
% the correct bar position - never a stale bar.
%
% USAGE: edit the parameters, make sure the G4 Host is running, then run.
%        Start this script first (so the display is live), then start the
%        FicTrac gate script that drives ADC0.

% =========================================================
% PARAMETERS - edit these to suit your experiment
% =========================================================

% Experiment folder
exp_folder   = 'C:\Users\Fisher Lab\Documents\GitHub\G4_Display_Tools\PControl_Matlab\Experiment';
pattern_id   = 16;       % pattern 16: 192 x-frames, frame 185 is set DARK (the strobe blank)

% Trial structure
trial_dur    = 360;      % seconds

% Mode 7 gain calibration: frame_index = gain * (voltage + offset)
% The blank/dark x-frame (index 185) and its voltage are defined on the FicTrac
% side (socket_client_strobe.py) and MUST use this same gain/offset mapping.
num_x_frames  = 192;     % total x-frames in pattern 16 (0..191); frame 185 is dark
voltage_range = 10;      % max voltage from your ADC0 source (V)
gain          = round(num_x_frames / voltage_range);   % = 19
offset        = 0;

% Analog output (optional experiment marker only - NOT the strobe anymore).
% The strobe on/off marker should be generated by the FicTrac gate script so
% it is phase-aligned with the actual voltage switching. Left here in case
% you still want a static level or a hardware trigger.
ao_channel   = 6;
ao_low_val   = 0;

% =========================================================
% CONNECT & CONFIGURE
% =========================================================
ctlr = PanelsController();
ctlr.open(true);

ctlr.setRootDirectory(exp_folder);
ctlr.setPatternID(pattern_id);
ctlr.setControlMode(7);          % ADC sets x index
ctlr.setGain(gain, offset);

ctlr.setActiveAOChannels(2);
ctlr.setAO(ao_channel, ao_low_val);

% =========================================================
% START LOG
% =========================================================
log_started = ctlr.startLog();
if ~log_started
    warning('Log failed to start. Check G4 Host.');
    ctlr.close();
    return;
end

% =========================================================
% RUN - ONE continuous, non-blocking startDisplay
% =========================================================
% startDisplay duration is in deciSeconds (tenths of a second), max 65535
% (~109 min). We never call stopDisplay during the trial, so the ADC is
% never frozen and there is no stale-position flash.
deci = trial_dur * 10;
if deci > 65535
    deci = 65535;   % clamp to the command's max; see note below for longer trials
    warning('trial_dur exceeds the 65535 deciSecond limit; clamping display to ~109 min.');
end

fprintf('Display running continuously (%.1f s). Start the FicTrac gate now.\n', trial_dur);
ctlr.startDisplay(deci, false);  % false = non-blocking; MATLAB continues below

% Idle-wait for the trial to elapse. MATLAB sends NO position/strobe commands
% here - the ADC0 voltage (from the FicTrac gate script) does everything.
t_trial = tic;
while toc(t_trial) < trial_dur
    pause(0.05);
end

% =========================================================
% STOP AND CLOSE
% =========================================================
ctlr.setAO(ao_channel, ao_low_val);
ctlr.stopDisplay();
ctlr.stopLog('timeout', 60.0, 'showTimeoutDialog', true);
ctlr.close();

fprintf('Done.\n');

% -------------------------------------------------------------------------
% NOTE on trials longer than ~109 min:
% Re-issuing startDisplay mid-trial would reintroduce the stale flash, so for
% very long trials prefer a longer single run or split the experiment into
% blocks with the animal briefly in true darkness between them (the FicTrac
% gate holding V_BLANK), which avoids a visible stale bar at each restart.
% -------------------------------------------------------------------------
